<a href="https://colab.research.google.com/github/Karthik5412/News-Classifier/blob/master/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing libraries

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np
import nltk as nl
import matplotlib.pyplot as plt
import seaborn

In [3]:
bussiness = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/business_data.csv')

education = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/education_data.csv')

entertainment = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/entertainment_data.csv')

sports = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/sports_data.csv')

technology = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/technology_data.csv')

In [4]:
import sklearn
print(f"Colab scikit-learn version: {sklearn.__version__}")

Colab scikit-learn version: 1.8.0

In [5]:
!pip install --upgrade scikit-learn==1.8.0

Requirement already satisfied: scikit-learn==1.8.0 in /usr/local/lib/python3.12/dist-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.8.0) (2.0.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.8.0) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.8.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.8.0) (3.6.0)

In [6]:
df = pd.concat([bussiness, education, entertainment, sports, technology], axis= 0)

df = df.sample(frac= 1).reset_index(drop= True)

df

,headlines,description,content,url,category
0,"In FSSAI index, nearly all major states slip o...",After adjusting for a new parameter included i...,Four years after the Food Safety and Standards...,https://indianexpress.com/article/business/in-...,business
1,5 launchers for UI customisations to make the ...,These five launchers can fully transform the l...,A smartphone is a highly customisable device. ...,https://indianexpress.com/article/technology/t...,technology
2,"She dabbled in karting and badminton. Now, Esh...","Daughter of a rally driver, 19-year-old wins I...","Growing up in Hyderabad, a young Esha Singh wo...",https://indianexpress.com/article/sports/sport...,sports
3,AP ECET 2023 Counselling: Phase 1 registration...,Candidates can apply for the counselling by vi...,AP ECET 2023 The department of technical educa...,https://indianexpress.com/article/education/ap...,education
4,My dear students | The movie Air and its take ...,"Nuggehalli writes: ""Air’s underlying premise i...","(‘My dear students’, a fortnightly column that...",https://indianexpress.com/article/education/my...,education
...,...,...,...,...,...
9995,BITS Pilani VC Ramgopal Rao gets VLSI Lifetime...,The VLSI Lifetime Achievement Award recognises...,"Professor Ramgopal Rao, the Vice Chancellor of...",https://indianexpress.com/article/education/bi...,education
9996,"JEE, NEET 2024: Entrance exam for Bihar board’...",JEE Main 2024: The admit cards for the admissi...,JEE Main 2024: The Bihar School Examination Bo...,https://indianexpress.com/article/education/je...,education
9997,Ravindra Jadeja has a better batting average t...,IND vs AUS: Axar Patel too has shown he can be...,IND vs AUS: A trio of spinners who could win g...,https://indianexpress.com/article/sports/crick...,sports
9998,Naga Chaitanya on streaming debut with Dhootha...,Actor Naga Chaitanya Akkineni plays a journali...,Actor Naga Chaitanya Akkineni plays a journali...,https://indianexpress.com/article/entertainmen...,entertainment
9999,Check fellowships for writing science books,The recipients of the full fellowship will get...,The Foundation for Advancing Science and Techn...,https://indianexpress.com/article/education/sc...,education

In [7]:
df['category'].value_counts()

category
business         2000
technology       2000
sports           2000
education        2000
entertainment    2000
Name: count, dtype: int64

In [8]:
df.isna().sum()

headlines      0
description    0
content        0
url            0
category       0
dtype: int64

In [9]:
df.shape

(10000, 5)

In [10]:
df = df.drop_duplicates()
df.shape

(10000, 5)

In [11]:
df

,headlines,description,content,url,category
0,"In FSSAI index, nearly all major states slip o...",After adjusting for a new parameter included i...,Four years after the Food Safety and Standards...,https://indianexpress.com/article/business/in-...,business
1,5 launchers for UI customisations to make the ...,These five launchers can fully transform the l...,A smartphone is a highly customisable device. ...,https://indianexpress.com/article/technology/t...,technology
2,"She dabbled in karting and badminton. Now, Esh...","Daughter of a rally driver, 19-year-old wins I...","Growing up in Hyderabad, a young Esha Singh wo...",https://indianexpress.com/article/sports/sport...,sports
3,AP ECET 2023 Counselling: Phase 1 registration...,Candidates can apply for the counselling by vi...,AP ECET 2023 The department of technical educa...,https://indianexpress.com/article/education/ap...,education
4,My dear students | The movie Air and its take ...,"Nuggehalli writes: ""Air’s underlying premise i...","(‘My dear students’, a fortnightly column that...",https://indianexpress.com/article/education/my...,education
...,...,...,...,...,...
9995,BITS Pilani VC Ramgopal Rao gets VLSI Lifetime...,The VLSI Lifetime Achievement Award recognises...,"Professor Ramgopal Rao, the Vice Chancellor of...",https://indianexpress.com/article/education/bi...,education
9996,"JEE, NEET 2024: Entrance exam for Bihar board’...",JEE Main 2024: The admit cards for the admissi...,JEE Main 2024: The Bihar School Examination Bo...,https://indianexpress.com/article/education/je...,education
9997,Ravindra Jadeja has a better batting average t...,IND vs AUS: Axar Patel too has shown he can be...,IND vs AUS: A trio of spinners who could win g...,https://indianexpress.com/article/sports/crick...,sports
9998,Naga Chaitanya on streaming debut with Dhootha...,Actor Naga Chaitanya Akkineni plays a journali...,Actor Naga Chaitanya Akkineni plays a journali...,https://indianexpress.com/article/entertainmen...,entertainment
9999,Check fellowships for writing science books,The recipients of the full fellowship will get...,The Foundation for Advancing Science and Techn...,https://indianexpress.com/article/education/sc...,education

In [12]:
# Dropping unwanted columns for this

df = df.drop(columns= ['url'])
df_copy = df.copy()
df

,headlines,description,content,category
0,"In FSSAI index, nearly all major states slip o...",After adjusting for a new parameter included i...,Four years after the Food Safety and Standards...,business
1,5 launchers for UI customisations to make the ...,These five launchers can fully transform the l...,A smartphone is a highly customisable device. ...,technology
2,"She dabbled in karting and badminton. Now, Esh...","Daughter of a rally driver, 19-year-old wins I...","Growing up in Hyderabad, a young Esha Singh wo...",sports
3,AP ECET 2023 Counselling: Phase 1 registration...,Candidates can apply for the counselling by vi...,AP ECET 2023 The department of technical educa...,education
4,My dear students | The movie Air and its take ...,"Nuggehalli writes: ""Air’s underlying premise i...","(‘My dear students’, a fortnightly column that...",education
...,...,...,...,...
9995,BITS Pilani VC Ramgopal Rao gets VLSI Lifetime...,The VLSI Lifetime Achievement Award recognises...,"Professor Ramgopal Rao, the Vice Chancellor of...",education
9996,"JEE, NEET 2024: Entrance exam for Bihar board’...",JEE Main 2024: The admit cards for the admissi...,JEE Main 2024: The Bihar School Examination Bo...,education
9997,Ravindra Jadeja has a better batting average t...,IND vs AUS: Axar Patel too has shown he can be...,IND vs AUS: A trio of spinners who could win g...,sports
9998,Naga Chaitanya on streaming debut with Dhootha...,Actor Naga Chaitanya Akkineni plays a journali...,Actor Naga Chaitanya Akkineni plays a journali...,entertainment
9999,Check fellowships for writing science books,The recipients of the full fellowship will get...,The Foundation for Advancing Science and Techn...,education

### Making Pipeline

In [13]:
from sklearn.base import BaseEstimator, TransformerMixin
import re
import string

class processing(BaseEstimator,TransformerMixin) :
    def fit(self, x, y=None ) :
        return self

    def healper(self, x):
        x = re.sub(r'[^a-zA-z\s]','',x.lower())
        return ' '.join(x.split())

    def transform(self, x) :
        combined = (x['headlines'].astype(str) + ' ' +
                    x['description'].astype(str) + ' ' +
                    x['content'].astype(str))

        return combined.apply(self.healper).tolist()

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

text_pipe = Pipeline([
    ('Text',processing()),
    ('Vectorizer', TfidfVectorizer(stop_words='english'))
])

prep_pipe = ColumnTransformer([
    ('Processing', text_pipe,['headlines', 'description', 'content'])
], remainder= 'passthrough')

pipe = Pipeline([
    ('preprocessing', prep_pipe),
    ('Classifier', LogisticRegression(max_iter= 1000, class_weight= 'balanced'))
])

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['enc'] = le.fit_transform(df['category'])

In [16]:
df['enc'].value_counts()

enc
0    2000
4    2000
3    2000
1    2000
2    2000
Name: count, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['category', 'enc']), df['enc'], test_size= 0.33, random_state= 42)

In [18]:
x_train

,headlines,description,content
8371,Angel One slips 7% after NSE imposes penalties,Netweb Technologies' IPO aims to raise 631 cro...,Homegrown server maker Netweb Technologies Ind...
5027,"Imran Khan dances on ‘Pappu Can’t Dance’, Ira ...",Imran Khan enjoyed cousin Ira Khan's wedding c...,Actor Aamir Khan’s daughter Ira Khan married N...
9234,"Karnataka forms new textbook revision panel, g...",The primary mandate of the 37-member committee...,The Karnataka government has formed a new text...
3944,Chandrayaan-3 lander establishes communication...,The orbiter had played a role in identifying a...,Ahead of its scheduled Moon landing on Wednesd...
6862,No written communication from I-T Dept on sear...,This came a day after the I-T Department issue...,Cable and wire manufacturer Polycab India reit...
...,...,...,...
5734,"FPIs sell 35,000 crore in domestic shares over...",September was the first month in the current f...,Concerns over higher-for-longer interest rates...
5191,"Telangana TOSS SSC, Intermediate October 2023 ...",TOSS 2023 Exam: While the Telangana open schoo...,The Telangana Open School Society (TOSS) has a...
5390,"Bill on data protection gets Cabinet approval,...","HDFC, the parent of HDFC Bank merged into the ...",JSW Steel Ltd will replace Housing Development...
860,"Time for Ishan, Hooda to fire as captain Pandy...",India were caught in a spin web on the Ranchi ...,India will have to raise their game a few notc...
7270,Vedang Raina denies rumours of dating Khushi K...,"In a recent interview, Vedang Raina clarified ...",The Archies actor Vedang Raina was teased abou...

In [19]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Processing',
                                                  Pipeline(steps=[('Text',
                                                                   processing()),
                                                                  ('Vectorizer',
                                                                   TfidfVectorizer(stop_words='english'))]),
                                                  ['headlines', 'description',
                                                   'content'])])),
                ('Classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [20]:
pred = pipe.predict(x_test)

In [21]:
y_test

6252    4
4684    2
1731    2
4742    3
4521    2
       ..
1744    2
9754    2
6094    1
8781    1
9401    1
Name: enc, Length: 3300, dtype: int64

In [22]:
pred

array([4, 2, 2, ..., 1, 1, 1])

In [23]:
from sklearn.metrics import accuracy_score, classification_report

acc = accuracy_score(y_true= y_test, y_pred= pred)

acc

0.9854545454545455

In [24]:
pipe.score(x_train, y_train)

0.9944776119402985

In [25]:
pipe.score(x_test, y_test)

0.9854545454545455

In [26]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       654
           1       1.00      1.00      1.00       650
           2       1.00      1.00      1.00       650
           3       0.99      0.99      0.99       675
           4       0.97      0.97      0.97       671

    accuracy                           0.99      3300
   macro avg       0.99      0.99      0.99      3300
weighted avg       0.99      0.99      0.99      3300

In [27]:
import joblib

joblib.dump(pipe, 'Pipeline_new.plk')
joblib.dump(le, 'Label_encoder.plk')

['Label_encoder.plk']