### Importing libraries

In [1]:
import pandas as pd
import numpy as np
import nltk as nl
import matplotlib.pyplot as plt
import seaborn

In [2]:
df = pd.read_json('News_Category_Dataset_v3.json', lines= True)
df

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28

In [3]:
df.isna().sum()

link                 0
headline             0
category             0
short_description    0
authors              0
date                 0
dtype: int64

In [4]:
df = df.drop_duplicates()

In [5]:
df

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28

In [6]:
# Dropping unwanted columns for this

df = df.drop(columns= ['link','authors'])
df_copy = df.copy()
df

,headline,category,short_description,date
0,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,2022-09-23
1,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,2022-09-23
2,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",2022-09-23
3,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",2022-09-23
4,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,2022-09-22
...,...,...,...,...
209522,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,2012-01-28
209523,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",2012-01-28
209524,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",2012-01-28
209525,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,2012-01-28
209526,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,2012-01-28

In [8]:
from tfr import processing_text, processing_date

prep = processing_text()
dot = processing_date()

df[['headline', 'category', 'short_description']] = prep.fit_transform(df[['headline', 'category', 'short_description']])

df

,headline,category,short_description,date
0,over million americans roll up sleeves for om...,us news,health experts said it is too early to predict...,2022-09-23
1,american airlines flyer charged banned for lif...,us news,he was subdued by passengers and crew when he ...,2022-09-23
2,of the funniest tweets about cats and dogs th...,comedy,until you have a dog you dont understand what ...,2022-09-23
3,the funniest tweets from parents this week sept,parenting,accidentally put grownup toothpaste on my todd...,2022-09-23
4,woman who called cops on black birdwatcher los...,us news,amy cooper accused investment firm franklin te...,2022-09-22
...,...,...,...,...
209522,rim ceo thorsten heins significant plans for b...,tech,verizon wireless and att are already promoting...,2012-01-28
209523,maria sharapova stunned by victoria azarenka i...,sports,afterward azarenka more effusive with the pres...,2012-01-28
209524,giants over patriots jets over colts among mo...,sports,leading up to super bowl xlvi the most talked ...,2012-01-28
209525,aldon smith arrested ers linebacker busted for...,sports,correction an earlier version of this story in...,2012-01-28
209526,dwight howard rips teammates after magic loss ...,sports,the fivetime allstar center tore into his team...,2012-01-28

In [9]:
dot.fit_transform(df)

,headline,category,short_description,year,day_sine,day_cos,month_sine,month_cos,weekday_sine,weekday_cos
0,over million americans roll up sleeves for om...,us news,health experts said it is too early to predict...,2022,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
1,american airlines flyer charged banned for lif...,us news,he was subdued by passengers and crew when he ...,2022,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
2,of the funniest tweets about cats and dogs th...,comedy,until you have a dog you dont understand what ...,2022,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
3,the funniest tweets from parents this week sept,parenting,accidentally put grownup toothpaste on my todd...,2022,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
4,woman who called cops on black birdwatcher los...,us news,amy cooper accused investment firm franklin te...,2022,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
...,...,...,...,...,...,...,...,...,...,...
209522,rim ceo thorsten heins significant plans for b...,tech,verizon wireless and att are already promoting...,2012,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
209523,maria sharapova stunned by victoria azarenka i...,sports,afterward azarenka more effusive with the pres...,2012,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
209524,giants over patriots jets over colts among mo...,sports,leading up to super bowl xlvi the most talked ...,2012,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
209525,aldon smith arrested ers linebacker busted for...,sports,correction an earlier version of this story in...,2012,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
209526,dwight howard rips teammates after magic loss ...,sports,the fivetime allstar center tore into his team...,2012,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813

In [10]:
df

,headline,category,short_description,date,weekday,day,month,year,day_sine,day_cos,month_sine,month_cos,weekday_sine,weekday_cos
0,over million americans roll up sleeves for om...,us news,health experts said it is too early to predict...,2022-09-23,4,23,9,2022,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
1,american airlines flyer charged banned for lif...,us news,he was subdued by passengers and crew when he ...,2022-09-23,4,23,9,2022,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
2,of the funniest tweets about cats and dogs th...,comedy,until you have a dog you dont understand what ...,2022-09-23,4,23,9,2022,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
3,the funniest tweets from parents this week sept,parenting,accidentally put grownup toothpaste on my todd...,2022-09-23,4,23,9,2022,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
4,woman who called cops on black birdwatcher los...,us news,amy cooper accused investment firm franklin te...,2022-09-22,3,22,9,2022,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209522,rim ceo thorsten heins significant plans for b...,tech,verizon wireless and att are already promoting...,2012-01-28,5,28,1,2012,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
209523,maria sharapova stunned by victoria azarenka i...,sports,afterward azarenka more effusive with the pres...,2012-01-28,5,28,1,2012,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
209524,giants over patriots jets over colts among mo...,sports,leading up to super bowl xlvi the most talked ...,2012-01-28,5,28,1,2012,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
209525,aldon smith arrested ers linebacker busted for...,sports,correction an earlier version of this story in...,2012-01-28,5,28,1,2012,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813
209526,dwight howard rips teammates after magic loss ...,sports,the fivetime allstar center tore into his team...,2012-01-28,5,28,1,2012,-0.032252,0.99948,-0.083237,0.99653,-0.142372,0.989813

### Making Pipeline

In [19]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

prep_pipe = ColumnTransformer([
    ('Text Processing', processing_text(),['headline', 'short_description']),
    ('Date Processing', processing_date(),['date']),
], remainder= 'passthrough')

pipe = Pipeline([
    ('preprocessing', prep_pipe)
])
pipe.fit_transform(df_copy.drop(columns='category'))

array([['over  million americans roll up sleeves for omicrontargeted covid boosters',
        'health experts said it is too early to predict whether demand would match up with the  million doses of the new boosters the us ordered for the fall',
        2022.0, ..., 0.996529786700559, -0.14237172979226415,
        0.989813260446615],
       ['american airlines flyer charged banned for life after punching flight attendant on video',
        'he was subdued by passengers and crew when he fled to the back of the aircraft after the confrontation according to the us attorneys office in los angeles',
        2022.0, ..., 0.996529786700559, -0.14237172979226415,
        0.989813260446615],
       [' of the funniest tweets about cats and dogs this week sept ',
        'until you have a dog you dont understand what could be eaten',
        2022.0, ..., 0.996529786700559, -0.14237172979226415,
        0.989813260446615],
       ...,
       ['giants over patriots jets over colts among  most improbable super bowl upsets of all time videos',
        'leading up to super bowl xlvi the most talked about game could end up being one that occurred a few years ago after all',
        2012.0, ..., 0.9965297867005595, -0.14237172979226437,
        0.989813260446615],
       ['aldon smith arrested ers linebacker busted for dui',
        'correction an earlier version of this story incorrectly stated the location of ktvu and the  league leader in sacks',
        2012.0, ..., 0.9965297867005595, -0.14237172979226437,
        0.989813260446615],
       ['dwight howard rips teammates after magic loss to hornets',
        'the fivetime allstar center tore into his teammates friday night after orlando committed  turnovers en route to losing',
        2012.0, ..., 0.9965297867005595, -0.14237172979226437,
        0.989813260446615]], shape=(209514, 9), dtype=object)

In [20]:
text_pipe = Pipeline([
    ('Text', processing_text()),
    ('Vec', TfidfVectorizer(stop_words= 'english', lowercase= True))
])

prep_pipe = ColumnTransformer([
    ('Text Processing', text_pipe,['headline', 'short_description']),
    ('Date Processing', processing_date(),['date']),
], remainder= 'passthrough')

pipe = Pipeline([
    ('preprocessing', prep_pipe)
])
pipe.fit_transform(df_copy.drop(columns='category'))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 209514

In [24]:
TfidfVectorizer(stop_words='english').fit_transform(processing_text().fit_transform(df[['headline', 'short_description']])['headline'])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1307300 stored elements and shape (209514, 66531)>